ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone_number VARCHAR(30);

ALTER TABLE wash_calendar
    ADD COLUMN IF NOT EXISTS accepted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE cars
    ADD COLUMN IF NOT EXISTS status VARCHAR(100);
